### Numpy
NumPy is a fundamentall library for scientific computing in Python. it provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this notebook, we will cover the basics of numpy, focusing on arrays and vectorized operations.

In [2]:
import numpy as np

## Create arrays using the numpy library
## create a 1D array

arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape) ## it will give the dimwnsion of the array

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [4]:
arr2 = np.array([1,2,3,4,5])

## reshaing the array 
arr2.reshape(1,5)

# arr2.reshape(1,4) ### It will give error as reshaping is not possible

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2.shape

(2, 5)

In [6]:
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
## Creating array with randon numbers
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
## Some inbuilt functions of numpy
np.ones((3,4)) ## Creating array of 1's

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
## Creating the identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
### attributes of  numpy array

arr= np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape)
print("Number of dimensions: ",arr.ndim)
print("Size (number of elements: )",arr.size)
print("Data Type: ",arr.dtype)
print("Item Size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions:  2
Size (number of elements: ) 6
Data Type:  int64
Item Size (in bytes): 8


In [14]:
#### NumPy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition:",arr1+arr2)

## Element wise Substraction
print("Subtraction: ",arr1-arr2)

## Element wise Multiplication
print("Multiplication:",arr1*arr2)

## Element wise division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
## Universal functions
arr = np.array([1,2,3,4,5,6])

## Square root
print("Sqaure root: ",np.sqrt(arr))

## Exponential
print("Exponential: ",np.exp(arr))

## Sine
print("Sine:",np.sin(arr))

## Natural Log
print("Log:",np.log(arr))

Sqaure root:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
## array Slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
print(arr[0][0]) ## Accesing the 1st element

1


In [23]:
print(arr[1][2]) #7
print(arr[1][3]) #8

7
8


In [24]:
## 7 8
## 11 12
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [25]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [26]:
### Modifying the array elements
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [27]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [29]:
### 1. Statistical Concepts --> Normalization

## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Performing the normalization
normaliized_data = (data-mean)/std_dev
print("Normalized_data:",normaliized_data)

Normalized_data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean: ",mean)

## Median
median = np.median(data)
print("Median: ",median)

## Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ",std_dev)

## Variance
variance = np.var(data)
print("Variance: ",variance)


Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [35]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
print(data[data>5])
print(data[(data>5) & (data <8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7]
